POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "phantchase",
    "password": "Loncace123.."
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "phantchase",
    "password": "Loncace123.."
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTAyYTRmNDk5NjcxMTJjYTAzODY1NjgiLCJpYXQiOjE2Mjc1NjMyNTd9.M29E103uVmOBtRqDiYkCLOQbGSevjCg7J7B5-WKStMg

{
    "title": "my second post",
    "description": "shopping",
    "url": "shopee.com",
    "status": "LEARNED"
}

###

GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTAyYTRmNDk5NjcxMTJjYTAzODY1NjgiLCJpYXQiOjE2Mjc1NjM5NDB9.no6e06rqzgnyaiuq5FTwviDtNJQfw5CcCvgjelGUpyg

###
PUT http://localhost:5000/api/posts/6102a788c4e1a01ee0fa390a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTAyYTRmNDk5NjcxMTJjYTAzODY1NjgiLCJpYXQiOjE2Mjc1NjM5NDB9.no6e06rqzgnyaiuq5FTwviDtNJQfw5CcCvgjelGUpyg

{
     "title": "VueA",
    "description": "Vueee",
    "url": "vue.org",
    "status": "LEARNING"
}
